services:

  #Nginx Service
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      #- ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl:/etc/ssl
      - ./web:/var/www/html
      - ./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template
    #depends_on:
    #  - php
    #  - mysql
    #  - redis
    networks:
      - app

  #PHP Service
  php:
    build:
      context: ./etc/php
      dockerfile: Dockerfile
    #image: php:${PHP_VERSION}
    container_name: ${PROJECT_NAME}_php
    restart: always
    tty: true
    #environment:
    #  SERVICE_NAME: app
    #  SERVICE_TAGS: dev
    working_dir: /var/www/html/app
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web:/var/www/html
    networks:
      - app

  #MySQL Service
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}_mysql
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      #- ./data/mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - app

  #PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: ${PROJECT_NAME}_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    depends_on:
      - mysql
    networks:
      - app

  #Redis Service
  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${PROJECT_NAME}_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./data/redis/conf:/usr/local/etc/redis
      - .//data/redis/log:/log
    restart: always
    networks:
      - app

#Docker Networks
networks:
  app:
    driver: bridge

#Volumes
volumes:
  mysql:
    driver: local
  redis:
    driver: local